@startuml

top to bottom direction

node "Kubernetes cluster" {
  boundary "Kube API Server" as K8sAPI

  rectangle "Kubernetes" as K8s

  K8sAPI -> K8s

  cloud "<i>Orange button</i> staging" as OBS #OldLace {
    frame "Common infrastructure" #lightcyan {
      database "Redis" as OBR #PowderBlue
      database "Postgres" as OBP #PowderBlue
      boundary "nginx" as OBN #PowderBlue
    }

    rectangle "Server with an <i>orange button</i>" as OBSer #Wheat

    OBSer -down-> OBR
    OBSer -down-> OBP
    OBN -right-> OBSer
  }

  cloud "<i>Green button</i> staging" as GBS #technology {
    frame "Common infrastructure " #lightcyan {
      database "Redis" as GBR #PowderBlue
      database "Postgres" as GBP #PowderBlue
      boundary "nginx" as GBN #PowderBlue
    }

    rectangle "Server with a <i>green button</i>" as GBSer #Greenyellow

    GBSer -down-> GBR
    GBSer -down-> GBP
    GBN -right-> GBSer
  }

  K8s -down-> OBS : create the staging
  K8s -down-> GBS : create the staging
}


node Octopod {
  boundary "Web UI" as UI
  rectangle "Octopod Server" as OctoS
  rectangle "Staging control scripts" as SCS

  UI -> OctoS
  OctoS -> SCS : delegates k8s logic to control script
}

SCS -down-> K8sAPI : set up the stagings


actor Developer

Developer -down-> UI : Specifies the git comit hash to deploy in the web UI

@enduml
