sequenceDiagram
    participant octo CLI
    participant Octopod Server
    participant PostgreSQL
    participant UI
    participant Octopod Server/BgWorker
    participant Octopod Server/StatusUpdater
    participant ControlScripts
    participant KubeAPI
    octo CLI->>Octopod Server: create(name, tag, [override])
    Octopod Server->>PostgreSQL: store config, status=UpdatePending
    alt name not found
        PostgreSQL-->>Octopod Server: error: name not found
        Octopod Server-->>octo CLI: error: name not found
    else
        alt tag not found
            Octopod Server-->>octo CLI: error: tag not found
        else
            PostgreSQL-->>Octopod Server: ok
            Octopod Server-xUI: event FrontendPleaseUpdateEverything
            UI->>Octopod Server: get deployments info
            Octopod Server-->UI: deployments info
            Octopod Server->>Octopod Server/BgWorker: update
            Octopod Server-->>octo CLI: done
            Octopod Server/BgWorker->>ControlScripts: update
            ControlScripts->>KubeAPI: upgrade deployment
            KubeAPI-->>ControlScripts: done
            ControlScripts-->>Octopod Server/BgWorker: done
            Octopod Server/BgWorker->>PostgreSQL: write logs
            Octopod Server/BgWorker-xUI: event FrontendPleaseUpdateEverything
            UI->>Octopod Server: get deployments info
            Octopod Server-->UI: deployments info
            Note over Octopod Server/StatusUpdater: wait 5 minutes
            loop check deployment status every 30 seconds
                Octopod Server/StatusUpdater->>PostgreSQL: status=Running/Failure
                Octopod Server/StatusUpdater-xUI: event FrontendPleaseUpdateEverything
                UI->>Octopod Server: get deployments info
                Octopod Server-->UI: deployments info
            end
        end
    end
