stateDiagram-v2
    [*] --> CreatePending: create
    Running --> UpdatePending: update
    Failure --> UpdatePending: update
    Running --> ArchivePending: archive
    Failure --> ArchivePending: archive
    Archived --> CreatePending: restore
    Archived --> [*]: cleanup
    Running --> Failure: 30s passed and 'check' said "nok"
    Failure --> Running: 30s passed and 'check' said "ok"
    CreatePending --> Running: 5m passed and 'check' said "ok"
    CreatePending --> Failure: 5m passed and 'check' said "nok"
    UpdatePending --> Running: 5m passed and 'check' said "ok"
    UpdatePending --> Failure: 5m passed and 'check' said "nok"
    ArchivePending --> Archived: 30s passed and 'archive_check' said "ok"
    ArchivePending --> ArchivePending: 30s passed and 'archive_check' said "nok"
    Archived --> CleanupFailed
