sequenceDiagram
    participant UI
    participant Octopod Server
    participant PostgreSQL
    participant Octopod Server/BgWorker
    participant Octopod Server/StatusUpdater
    participant ControlScripts
    participant KubeAPI
    UI->>Octopod Server: cleanup(name)
    Octopod Server->>Octopod Server/BgWorker: cleanup
    Octopod Server-->>UI: done
    Octopod Server/BgWorker->>ControlScripts: cleanup
    ControlScripts->>KubeAPI: cleanup deployment resources
    KubeAPI-->>ControlScripts: done
    ControlScripts-->>Octopod Server/BgWorker: done
    Octopod Server->>PostgreSQL: delete config and logs
    Octopod Server/BgWorker-xUI: event FrontendPleaseUpdateEverything
    UI->>Octopod Server: get deployments info
    Octopod Server-->>UI: deployments info
