sequenceDiagram
    participant octo CLI
    participant Octopod Server
    participant PostgreSQL
    participant UI
    participant Octopod Server/BgWorker
    participant Octopod Server/StatusUpdater
    participant ControlScripts
    participant KubeAPI
    octo CLI->>Octopod Server: cleanup(name)
    Octopod Server->>Octopod Server/BgWorker: cleanup
    Octopod Server-->>octo CLI: done
    Octopod Server/BgWorker->>ControlScripts: cleanup
    ControlScripts->>KubeAPI: cleanup deployment
    KubeAPI-->>ControlScripts: done
    ControlScripts-->>Octopod Server/BgWorker: done
    Octopod Server->>PostgreSQL: delete config and logs
    Octopod Server/BgWorker-xUI: event FrontendPleaseUpdateEverything
    UI->>Octopod Server: get deployments info
    Octopod Server-->>UI: deployments info
