sequenceDiagram
    participant DMC
    participant DMS
    participant PostgreSQL
    participant UI
    participant DMS/BgWorker
    participant DMS/StatusUpdater
    participant AppWrappers
    participant KubeAPI
    DMC->>DMS: cleanup(name)
    DMS->>DMS/BgWorker: cleanup
    DMS-->>DMC: done
    DMS/BgWorker->>AppWrappers: cleanup
    AppWrappers->>KubeAPI: cleanup staging
    KubeAPI-->>AppWrappers: done
    AppWrappers-->>DMS/BgWorker: done
    DMS->>PostgreSQL: delete config and logs
    DMS/BgWorker-xUI: event FrontendPleaseUpdateEverything
    UI->>DMS: get stagings info
    DMS-->>UI: stagings info
