resolver: lts-18.2

packages:
  - octo-cli
  - octopod-api
  - octopod-backend
  - octopod-common

extra-deps:
  - servant-websockets-2.0.0
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
