[core]
  engine = pg
  plan_file = sqitch.plan
top_dir = .
[engine "pg"]
  registry = sqitch_air
[deploy]
  verify = true
[rebase]
  verify = true
[target "air"]
  uri = dp:pg://octopod:123456@localhost:5432/octopod
