{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "octopodCliAuthSecretName" . }}
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  cli-secret: {{ include "octopodCliAuthSecret" . | b64enc }}
{{- end }}
