{{- $octopodAppAuthPassword := randAlphaNum 32 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octopod.fullname" . }}-nginx-config
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  app.conf: |
    server {
      listen 80 default_server;
      server_name _;
      root /www;
      index index.html;
      error_page 404 =200 /index.html;
    }
  config.json: |
    {
      "app_url": "{{ printf "%s://%s" (include "httpScheme" .) .Values.ingress.app.host}}",
      "ws_url": "{{ printf "%s://%s" (include "wsScheme" .) .Values.ingress.ws.host}}",
      "app_auth": "Basic {{ printf "octopod:%s" $octopodAppAuthPassword | b64enc }}",
      
      "kubernetes_dashboard_url_template": null
      
    }
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "octopodAppAuthSecretName" . }}
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
data:
  auth: {{ htpasswd "octopod" $octopodAppAuthPassword | b64enc }}
