apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-control-clusterrole
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "delete", "deletecollection"]
