name: "Common setup"
description: "Common setup steps"
inputs:
  cachixSigningKey:
    description: "Cachix signing key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install skopeo
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install skopeo

    - name: Increase swap
      shell: bash
      run: |
        free -h

        sudo swapoff /mnt/swapfile
        sudo fallocate -l 12G /mnt/swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile

        free -h

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/

    - name: Login to Cachix
      uses: cachix/cachix-action@v8
      with:
        name: octopod
        signingKey: ${{ inputs.cachixSigningKey }}

    - name: Allow kvm in Nix
      shell: bash
      run: |
        # enable required features (see https://github.com/cachix/install-nix-action/issues/19)
        mkdir -p ~/.config/nix
        echo "system-features = kvm" >> ~/.config/nix/nix.conf
