{{- if .Values.ingress.enabled -}}
{{- $fullName := include "octopod.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.enabled }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer | quote }}
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "http_502 error timeout"
    {{- with .Values.ingress.ui.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "uiIngressHost" . }}
      secretName: {{ $fullName }}-ui-tls
  {{- end }}
  rules:
    - host: {{ include "uiIngressHost" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.ports.ui }}
{{- end }}
