apiVersion: v1
kind: Service
metadata:
  name: {{ include "octopod.fullname" . }}
  labels:
    {{- include "octopod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $portName, $portNumber := .Values.service.ports }}
    - name: octopod-{{ $portName | lower }}
      port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
{{- end }}
  selector:
    {{- include "octopod.selectorLabels" . | nindent 4 }}
