name: "Push Docker Images"
description: "Push Docker Images"
inputs:
  tag:
    description: "The docker image tag to push."
    required: true
  docker_username:
    description: "The Docker Hub username"
    required: true
  docker_password:
    description: "The Docker Hub password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Push Docker Images to DockerHub
      shell: bash
      run: |
        skopeo copy docker-archive:$(nix-build ./nix -j auto -A octopod-server-container) docker://typeable/octopod:${{ inputs.tag }}
        skopeo copy docker-archive:$(nix-build ./nix -j auto -A octo-cli-container) docker://typeable/octo:${{ inputs.tag }}
