name: Build
on:
  push:
    branches:
      - master
      - develop
      - staging
  pull_request:
    branches:
      - master
      - develop
      - staging

jobs:
  check-formatting:
    name: Check Haskell formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Run fourmolu
        run: |
          nix-shell nix/ci.nix -j auto --run "git ls-files '*.hs' | xargs fourmolu -m inplace --ghc-opt -XRecursiveDo --ghc-opt -XTypeApplications"
          git diff --exit-code

  octo-macOS:
    name: macOS octo CLI Release (Stack)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: octo-cli-stack-${{ runner.os }}
      # TODO: Remove this step once https://github.com/actions/cache/issues/445 is resolved.
      - name: Fix macOS cache bug
        run: rm -rf ~/.stack/setup-exe-cache
      - name: Build
        run: stack build octo-cli --local-bin-path out --copy-bins
      - uses: actions/upload-artifact@v2
        with:
          name: octo-cli-macos
          path: out/octo
  octo-linux:
    name: Linux octo CLI Release (Nix)
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2
      - name: Common setup
        uses: ./.github/actions/common_setup
        with:
          cachixSigningKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Build
        run: nix-build -A projectCross.musl64.hsPkgs.octo-cli.components.exes.octo --arg prod true -j auto
      - uses: actions/upload-artifact@v2
        with:
          name: octo-cli-linux
          path: result/bin/octo
  docker-images:
    name: Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Common setup
        uses: ./.github/actions/common_setup
        with:
          cachixSigningKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - uses: actions/checkout@v2

      - name: Build Docker Images
        run: nix-build ./nix -j auto

      - name: Push Nightly Docker Images to DockerHub
        uses: ./.github/actions/push_docker_images
        with:
          tag: nightly

      - name: Rename Docker image archives
        run: |
          cp $(nix-build ./nix -j auto -A octopod-server-container) octo-cli-image.tar.gz
          cp $(nix-build ./nix -j auto -A octo-cli-container) octopod-server-image.tar.gz

      - name: Upload octo CLI Image
        uses: actions/upload-artifact@v2
        with:
          name: octo-cli-image
          path: octo-cli-image.tar.gz

      - name: Upload Octopod Server Image
        uses: actions/upload-artifact@v2
        with:
          name: octopod-server-image
          path: octopod-server-image.tar.gz
